name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'

jobs:
  checkout_code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  install_dependencies:
    needs: checkout_code
    runs-on: self-hosted
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check local npm cache
        id: local-cache
        run: |
          if [ -f ~/.npm/node_modules.tgz ]; then
            echo "::set-output name=cache_exists::true"
          else
            echo "::set-output name=cache_exists::false"
          fi

      - name: Restore local npm cache
        if: steps.local-cache.outputs.cache_exists == 'true'
        run: tar xzf ~/.npm/node_modules.tgz

      - name: Install dependencies
        if: steps.local-cache.outputs.cache_exists == 'false'
        run: npm ci

      - name: Save local npm cache
        if: steps.local-cache.outputs.cache_exists == 'false'
        run: |
          mkdir -p ~/.npm
          tar czf ~/.npm/node_modules.tgz node_modules

  sca_testing:
    needs: install_dependencies
    runs-on: self-hosted
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true  # Add this line

  build:
    needs: sca_testing
    runs-on: self-hosted
    steps:
      - name: Build
        run: npm run build
